

<TicketListScreen>:
    size_hint: 1,None

    canvas.before:
        Color:
            rgba: (1 , 1, 0 , 1)
        Rectangle:
            pos: self.pos
            size: self.size
    
    FloatLayout:
        
        BoxLayout:
            size_hint: 1,1
            orientation: 'vertical'

            BoxLayout:
                size_hint: 1, 0.2
                
            BoxLayout:
                size_hint: 1, 0.8
                
                

            













